# surflifegen/yolo_cli.py
"""
Command-Line Interface for SurfLifeGen-MLX YOLO Dataset Exporter (`surflifegen-yolo-export`).
Converts synthetic or real dataset folders into Ultralytics YOLOv8/YOLOv11 ready formats (`images/`, `labels/`, `data.yaml`).
"""

import argparse
from .yolo_exporter import YoloDatasetExporter


def main():
    parser = argparse.ArgumentParser(
        description="SurfLifeGen-MLX: Ultralytics YOLOv8/YOLOv11 Dataset Exporter (`surflifegen-yolo-export`)"
    )
    parser.add_argument(
        "--dataset-dir", "-d",
        required=True,
        help="Path to input directory generated by surflifegen, surflifegen-highway, or surflifegen-segment"
    )
    parser.add_argument(
        "--output-dir", "-o",
        default="./yolo_dataset",
        help="Path where the YOLO structured folder (`images/`, `labels/`, `data.yaml`) will be written"
    )
    parser.add_argument(
        "--split-ratio", "-s",
        type=float,
        default=0.8,
        help="Train vs validation split ratio (default: 0.8 for 80%% train / 20%% val)"
    )
    parser.add_argument(
        "--mode", "-m",
        choices=["auto", "detect", "segment"],
        default="auto",
        help="Export mode: 'detect' for bounding boxes, 'segment' for polygon masks, or 'auto' (default: auto)"
    )
    parser.add_argument(
        "--symlink",
        action="store_true",
        help="Use symlinks instead of copying PNG images to save disk space"
    )

    args = parser.parse_args()

    exporter = YoloDatasetExporter(
        dataset_dir=args.dataset_dir,
        output_dir=args.output_dir,
        split_ratio=args.split_ratio,
        mode=args.mode,
        copy_images=not args.symlink
    )
    exporter.export()


if __name__ == "__main__":
    main()
